"""Tests for the raster grid and terrain derivatives.

Slope and aspect are checked against analytically-known surfaces rather than golden arrays. A sign
error in the row convention flips aspect by 180 degrees and is invisible in a golden test that was
generated by the same buggy code.
"""

from __future__ import annotations

import numpy as np
import pytest

from japgo.geo import SHIZUOKA, Bounds, Raster, aspect, exceeds_grade, hillshade, roughness, slope

RES = 1.0


def _raster(data: np.ndarray, res: float = RES) -> Raster:
    h, w = data.shape
    return Raster(data.astype(np.float32), Bounds(0, 0, w * res, h * res), SHIZUOKA.crs)


def _plane(rows: int, cols: int, *, d_east: float = 0.0, d_north: float = 0.0) -> Raster:
    """A plane rising ``d_east`` m per metre eastward and ``d_north`` m per metre northward.

    Row 0 is the north edge, so northing decreases with row index.
    """
    r = np.arange(rows)[:, None]
    c = np.arange(cols)[None, :]
    northing = (rows - 1 - r) * RES
    easting = c * RES
    return _raster(easting * d_east + northing * d_north)


# ---------------------------------------------------------------------------------------------
# Raster
# ---------------------------------------------------------------------------------------------


def test_row_zero_is_the_north_edge():
    r = _raster(np.zeros((4, 4)))
    _, y_top = r.cell_centre(0, 0)
    _, y_bottom = r.cell_centre(3, 0)
    assert y_top > y_bottom


def test_index_of_roundtrips_with_cell_centre():
    r = _raster(np.zeros((5, 7)))
    for row in range(5):
        for col in range(7):
            x, y = r.cell_centre(row, col)
            assert r.index_of(x, y) == (row, col)


def test_rejects_geographic_crs():
    with pytest.raises(ValueError, match="geographic CRS"):
        Raster(np.zeros((2, 2), np.float32), Bounds(0, 0, 2, 2), 4326)


def test_rejects_non_2d_data():
    with pytest.raises(ValueError, match="2-D"):
        Raster(np.zeros((2, 2, 3), np.float32), Bounds(0, 0, 2, 2), SHIZUOKA.crs)


def test_downsample_averages_blocks():
    r = _raster(np.array([[1.0, 3.0], [5.0, 7.0]]))
    out = r.downsample(2)
    assert out.data.shape == (1, 1)
    assert out.data[0, 0] == pytest.approx(4.0)


def test_downsample_preserves_bounds_and_doubles_resolution():
    r = _raster(np.zeros((8, 8)))
    out = r.downsample(2)
    assert out.data.shape == (4, 4)
    assert out.resolution == pytest.approx(2.0)
    assert out.bounds.as_tuple() == pytest.approx(r.bounds.as_tuple())


def test_downsample_ignores_nan():
    r = _raster(np.array([[1.0, np.nan], [3.0, 5.0]]))
    assert r.downsample(2).data[0, 0] == pytest.approx(3.0)


def test_coverage_reports_data_fraction():
    data = np.full((2, 2), 1.0)
    data[0, 0] = np.nan
    assert _raster(data).coverage == pytest.approx(0.75)


def test_fill_gaps_closes_small_voids():
    data = np.ones((5, 5))
    data[2, 2] = np.nan
    filled = _raster(data).fill_gaps()
    assert filled.data[2, 2] == pytest.approx(1.0)
    assert filled.coverage == 1.0


def test_clip_to_snaps_outward_to_whole_cells():
    """The clip must not lose data at the edge, so it snaps outward and fully covers the request."""
    r = _raster(np.arange(100, dtype=float).reshape(10, 10))
    requested = Bounds(2, 2, 5, 5)
    out = r.clip_to(requested)

    assert out.bounds.minx <= requested.minx
    assert out.bounds.miny <= requested.miny
    assert out.bounds.maxx >= requested.maxx
    assert out.bounds.maxy >= requested.maxy
    # Never larger than one cell beyond the request on each side.
    assert out.bounds.width < requested.width + 2 * r.resolution
    assert out.resolution == pytest.approx(r.resolution)


def test_clip_outside_extent_raises():
    r = _raster(np.zeros((4, 4)))
    with pytest.raises(ValueError, match="do not intersect"):
        r.clip_to(Bounds(100, 100, 110, 110))


# ---------------------------------------------------------------------------------------------
# Slope
# ---------------------------------------------------------------------------------------------


def test_flat_terrain_has_zero_slope():
    assert np.allclose(slope(_plane(5, 5)).data, 0.0)


def test_slope_of_45_degree_plane():
    """1 m rise per 1 m run is 45 degrees, and 100% grade."""
    east = _plane(5, 5, d_east=1.0)
    assert slope(east).data[2, 2] == pytest.approx(45.0, abs=1e-4)
    assert slope(east, as_percent=True).data[2, 2] == pytest.approx(100.0, abs=1e-3)


def test_slope_is_direction_agnostic():
    """A 10% slope is 10% whether it runs east or north."""
    east = slope(_plane(7, 7, d_east=0.1), as_percent=True).data[3, 3]
    north = slope(_plane(7, 7, d_north=0.1), as_percent=True).data[3, 3]
    assert east == pytest.approx(north, abs=1e-6)
    assert east == pytest.approx(10.0, abs=1e-3)


def test_slope_scales_with_cell_size():
    """The same array at 2 m cells describes half the gradient."""
    data = np.tile(np.arange(5, dtype=float), (5, 1))
    fine = Raster(data.astype(np.float32), Bounds(0, 0, 5, 5), SHIZUOKA.crs)
    coarse = Raster(data.astype(np.float32), Bounds(0, 0, 10, 10), SHIZUOKA.crs)
    assert slope(fine, as_percent=True).data[2, 2] == pytest.approx(
        2 * slope(coarse, as_percent=True).data[2, 2]
    )


# ---------------------------------------------------------------------------------------------
# Aspect — the sign convention that is easy to get backwards
# ---------------------------------------------------------------------------------------------


def test_aspect_of_east_rising_plane_points_west():
    """Ground rising eastward drains west: compass 270."""
    assert aspect(_plane(5, 5, d_east=1.0)).data[2, 2] == pytest.approx(270.0, abs=1e-3)


def test_aspect_of_north_rising_plane_points_south():
    """Ground rising northward drains south: compass 180.

    This is the assertion that catches a flipped row convention.
    """
    assert aspect(_plane(5, 5, d_north=1.0)).data[2, 2] == pytest.approx(180.0, abs=1e-3)


def test_aspect_of_west_rising_plane_points_east():
    assert aspect(_plane(5, 5, d_east=-1.0)).data[2, 2] == pytest.approx(90.0, abs=1e-3)


def test_aspect_of_south_rising_plane_points_north():
    a = aspect(_plane(5, 5, d_north=-1.0)).data[2, 2]
    assert a == pytest.approx(0.0, abs=1e-3) or a == pytest.approx(360.0, abs=1e-3)


def test_flat_aspect_is_nan_not_zero():
    """0 is a real direction; conflating 'north-facing' with 'flat' corrupts circular statistics."""
    assert np.isnan(aspect(_plane(5, 5)).data[2, 2])


# ---------------------------------------------------------------------------------------------
# Roughness, hillshade, grade constraint
# ---------------------------------------------------------------------------------------------


def test_flat_terrain_has_zero_roughness():
    assert np.allclose(roughness(_plane(6, 6)).data, 0.0)


def test_broken_terrain_is_rougher_than_a_plane():
    rng = np.random.default_rng(0)
    broken = _raster(rng.normal(0, 5, (16, 16)))
    smooth = _plane(16, 16, d_east=0.1)
    assert np.nanmean(roughness(broken).data) > np.nanmean(roughness(smooth).data)


def test_roughness_window_must_be_odd():
    with pytest.raises(ValueError, match="odd"):
        roughness(_plane(5, 5), window=4)


def test_hillshade_is_brighter_on_slopes_facing_the_light():
    """Default azimuth is 315 (north-west), so north-west facing ground is lit."""
    nw_facing = _plane(9, 9, d_north=-0.5, d_east=0.5)  # drains north-west
    se_facing = _plane(9, 9, d_north=0.5, d_east=-0.5)
    assert hillshade(nw_facing).data[4, 4] < hillshade(se_facing).data[4, 4]


def test_exceeds_grade_flags_steep_cells():
    steep = _plane(5, 5, d_east=0.20)  # 20%
    gentle = _plane(5, 5, d_east=0.05)  # 5%
    assert exceeds_grade(steep, 12.0)[2, 2]
    assert not exceeds_grade(gentle, 12.0)[2, 2]


def test_nodata_propagates_into_derivatives():
    """np.pad(mode='edge') would invent plausible values at a void margin."""
    data = np.zeros((5, 5))
    data[2, 2] = np.nan
    r = _raster(data)
    assert np.isnan(slope(r).data[2, 2])
    assert np.isnan(roughness(r).data[2, 2])
    assert np.isnan(hillshade(r).data[2, 2])
